### ISSUE TITLE
Update on project?

### ISSUE THREAD

**Issue by chacham18** [litecoin-project/litecoin.network#1]
Any news about this? Where you stuck at? bitcoinifocharts enough?
Could we get data from there and just present it better in a Litecoin centered network dashboard?

The lack of a reliable network/block explorer link from the litecoin pages is not very good IMO:
- Litecoin.org links block explorer to this broken site: http://ltc.block-explorer.com/charts
- Litecoin.com website doesn't even have a link to any block explorer. I believe it's important to help users with a list of reliable block explorers

**Comment by losh11** [comment]
This is being worked on as part of the litecoin.com redesign. Including links to block-explorers and an API. After the API is ready for production, we will use the API and build a dashboard with a good ux. I've submitted a PR to replace the broken block-explorer on the .org site. 

For the meanwhile, I would recommend using insight.litecore.io and testnet.litecore.io. The API is documented in the repo README here: https://github.com/litecoin-project/insight-lite-api. Replace `/insight-lite-api` with `/api`.
